[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
runner = "elf2uf2-rs"
#runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[env]
DEFMT_LOG = "debug"